linters:
  enable:
    - bodyclose
    - gofmt
    - goimports
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - vet
  disable:
    - errcheck

run:
  deadline: 2m
